---
apiVersion: v1
kind: Service
metadata:
  name: iot-service
spec:
  type: NodePort
  selector:
    app: iot-dashboard
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30082 # Access via http://<minikube-ip>:30082